name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install
      - run: bun run build
